; ================================================================================
; Sprite DPLCs - generated by Flex 2 Sat Oct 02 2021 07:34:20 GMT-0700 (US Mountain Standard Time)
; ================================================================================

DATA3W8966YD7JJ:
	dc.w DATA3W8966YD7JJ_0-DATA3W8966YD7JJ, DATA3W8966YD7JJ_1-DATA3W8966YD7JJ
DATA3W8966YD7JJ_0: dc.b $0
DATA3W8966YD7JJ_1: dc.b $2
	dc.b $F0, $0
	dc.b $20, $10
	even