; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Oct 02 2021 07:34:19 GMT-0700 (US Mountain Standard Time)
; ================================================================================

DATA83K99TCKQ43:
	dc.w $0, DATA83K99TCKQ43_1-DATA83K99TCKQ43
DATA83K99TCKQ43_1: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $EC, $0, $0, $11, $8
	dc.b $B, $0, $0, $12, $F0
	even