; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Aug 14 2021 01:31:54 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATARSKSYXXHDS:
	dc.w $0, DATARSKSYXXHDS_1-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_2-DATARSKSYXXHDS, DATARSKSYXXHDS_3-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_4-DATARSKSYXXHDS, DATARSKSYXXHDS_5-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_6-DATARSKSYXXHDS, DATARSKSYXXHDS_7-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_8-DATARSKSYXXHDS, DATARSKSYXXHDS_9-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_A-DATARSKSYXXHDS, DATARSKSYXXHDS_B-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_C-DATARSKSYXXHDS, DATARSKSYXXHDS_D-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_E-DATARSKSYXXHDS, DATARSKSYXXHDS_F-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_10-DATARSKSYXXHDS, DATARSKSYXXHDS_11-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_12-DATARSKSYXXHDS, DATARSKSYXXHDS_13-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_14-DATARSKSYXXHDS, DATARSKSYXXHDS_15-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_16-DATARSKSYXXHDS, DATARSKSYXXHDS_17-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_18-DATARSKSYXXHDS, DATARSKSYXXHDS_19-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_1A-DATARSKSYXXHDS, DATARSKSYXXHDS_1B-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_1C-DATARSKSYXXHDS, DATARSKSYXXHDS_1D-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_1E-DATARSKSYXXHDS, DATARSKSYXXHDS_1F-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_20-DATARSKSYXXHDS, DATARSKSYXXHDS_21-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_22-DATARSKSYXXHDS, DATARSKSYXXHDS_23-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_24-DATARSKSYXXHDS, DATARSKSYXXHDS_25-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_26-DATARSKSYXXHDS, DATARSKSYXXHDS_27-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_28-DATARSKSYXXHDS, DATARSKSYXXHDS_29-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_2A-DATARSKSYXXHDS, DATARSKSYXXHDS_2B-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_2C-DATARSKSYXXHDS, DATARSKSYXXHDS_2D-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_2E-DATARSKSYXXHDS, DATARSKSYXXHDS_2F-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_30-DATARSKSYXXHDS, DATARSKSYXXHDS_31-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_32-DATARSKSYXXHDS, DATARSKSYXXHDS_33-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_34-DATARSKSYXXHDS, DATARSKSYXXHDS_35-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_36-DATARSKSYXXHDS, DATARSKSYXXHDS_37-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_38-DATARSKSYXXHDS, DATARSKSYXXHDS_39-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_3A-DATARSKSYXXHDS, DATARSKSYXXHDS_3B-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_3C-DATARSKSYXXHDS, DATARSKSYXXHDS_3D-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_3E-DATARSKSYXXHDS, DATARSKSYXXHDS_3F-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_40-DATARSKSYXXHDS, DATARSKSYXXHDS_41-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_42-DATARSKSYXXHDS, DATARSKSYXXHDS_43-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_44-DATARSKSYXXHDS, DATARSKSYXXHDS_45-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_46-DATARSKSYXXHDS, DATARSKSYXXHDS_47-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_48-DATARSKSYXXHDS, $0
	dc.w $0, $0
	dc.w DATARSKSYXXHDS_4C-DATARSKSYXXHDS, DATARSKSYXXHDS_4D-DATARSKSYXXHDS
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATARSKSYXXHDS_53-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_54-DATARSKSYXXHDS, DATARSKSYXXHDS_55-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_56-DATARSKSYXXHDS, DATARSKSYXXHDS_57-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_58-DATARSKSYXXHDS, DATARSKSYXXHDS_59-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_5A-DATARSKSYXXHDS, DATARSKSYXXHDS_5B-DATARSKSYXXHDS
	dc.w DATARSKSYXXHDS_5C-DATARSKSYXXHDS, DATARSKSYXXHDS_5D-DATARSKSYXXHDS
DATARSKSYXXHDS_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_3: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_4: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_6: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATARSKSYXXHDS_7: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATARSKSYXXHDS_8: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATARSKSYXXHDS_9: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATARSKSYXXHDS_A: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATARSKSYXXHDS_B: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATARSKSYXXHDS_C: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATARSKSYXXHDS_D: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATARSKSYXXHDS_E: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATARSKSYXXHDS_F: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATARSKSYXXHDS_10: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATARSKSYXXHDS_11: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATARSKSYXXHDS_12: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATARSKSYXXHDS_13: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATARSKSYXXHDS_14: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATARSKSYXXHDS_15: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATARSKSYXXHDS_16: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATARSKSYXXHDS_17: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATARSKSYXXHDS_18: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATARSKSYXXHDS_19: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATARSKSYXXHDS_1A: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATARSKSYXXHDS_1B: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATARSKSYXXHDS_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATARSKSYXXHDS_1D: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATARSKSYXXHDS_1E: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATARSKSYXXHDS_1F: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATARSKSYXXHDS_20: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATARSKSYXXHDS_21: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATARSKSYXXHDS_22: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATARSKSYXXHDS_23: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATARSKSYXXHDS_24: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATARSKSYXXHDS_25: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATARSKSYXXHDS_26: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $4, $0, $C, $6
	dc.b $F0, $0, $0, $E, $E
DATARSKSYXXHDS_27: dc.b $2
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $5, $0, $9, $5
DATARSKSYXXHDS_28: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $4, $0, $C, $5
	dc.b $F0, $0, $0, $E, $D
DATARSKSYXXHDS_29: dc.b $2
	dc.b $EF, $A, $0, $0, $EC
	dc.b $F7, $5, $0, $9, $4
DATARSKSYXXHDS_2A: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATARSKSYXXHDS_2B: dc.b $3
	dc.b $0, $A, $0, $0, $E4
	dc.b $F0, $5, $0, $9, $FC
	dc.b $0, $1, $0, $D, $FC
DATARSKSYXXHDS_2C: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATARSKSYXXHDS_2D: dc.b $3
	dc.b $0, $A, $0, $0, $E3
	dc.b $F0, $5, $0, $9, $FB
	dc.b $0, $1, $0, $D, $FB
DATARSKSYXXHDS_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATARSKSYXXHDS_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATARSKSYXXHDS_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATARSKSYXXHDS_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATARSKSYXXHDS_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATARSKSYXXHDS_33: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATARSKSYXXHDS_34: dc.b $1
	dc.b $F5, $F, $0, $0, $F2
DATARSKSYXXHDS_35: dc.b $2
	dc.b $EF, $F, $0, $0, $F2
	dc.b $F, $8, $0, $10, $F2
DATARSKSYXXHDS_36: dc.b $1
	dc.b $F5, $F, $0, $0, $F2
DATARSKSYXXHDS_37: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_38: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARSKSYXXHDS_39: dc.b $1
	dc.b $F9, $B, $0, $0, $F4
DATARSKSYXXHDS_3A: dc.b $2
	dc.b $EC, $B, $0, $0, $EE
	dc.b $C, $8, $0, $C, $EE
DATARSKSYXXHDS_3B: dc.b $2
	dc.b $ED, $B, $0, $0, $EB
	dc.b $D, $8, $0, $C, $EB
DATARSKSYXXHDS_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATARSKSYXXHDS_3D: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARSKSYXXHDS_3E: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARSKSYXXHDS_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATARSKSYXXHDS_40: dc.b $4
	dc.b $10, $4, $0, $0, $EC
	dc.b $F0, $B, $0, $2, $F4
	dc.b $E8, $4, $0, $E, $FC
	dc.b $10, $0, $0, $10, $4
DATARSKSYXXHDS_41: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATARSKSYXXHDS_42: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATARSKSYXXHDS_43: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATARSKSYXXHDS_44: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATARSKSYXXHDS_45: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATARSKSYXXHDS_46: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATARSKSYXXHDS_47: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATARSKSYXXHDS_48: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATARSKSYXXHDS_4C: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATARSKSYXXHDS_4D: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATARSKSYXXHDS_53: dc.b $2
	dc.b $F4, $A, $8, $0, $E8
	dc.b $FC, $8, $8, $9, $0
DATARSKSYXXHDS_54: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARSKSYXXHDS_55: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $FC, $0, $0, $10, $EA
	dc.b $C, $8, $0, $11, $FA
DATARSKSYXXHDS_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $1, $0, $E, $C
	dc.b $C, $C, $0, $10, $EC
DATARSKSYXXHDS_57: dc.b $4
	dc.b $EE, $B, $0, $0, $F4
	dc.b $F6, $1, $0, $C, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $4, $0, $11, $FC
DATARSKSYXXHDS_58: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $E8, $4, $0, $8, $F4
	dc.b $0, $A, $0, $A, $F4
	dc.b $F0, $1, $0, $13, $C
DATARSKSYXXHDS_59: dc.b $4
	dc.b $EE, $F, $0, $0, $F4
	dc.b $FE, $1, $0, $10, $14
	dc.b $6, $0, $0, $12, $EC
	dc.b $E, $1, $0, $13, $F4
DATARSKSYXXHDS_5A: dc.b $4
	dc.b $F5, $C, $0, $0, $E4
	dc.b $ED, $0, $0, $4, $F4
	dc.b $FD, $E, $0, $5, $F4
	dc.b $15, $4, $0, $11, $F4
DATARSKSYXXHDS_5B: dc.b $4
	dc.b $7, $D, $0, $0, $EC
	dc.b $EF, $A, $0, $8, $F4
	dc.b $17, $4, $0, $11, $FC
	dc.b $7, $1, $0, $13, $C
DATARSKSYXXHDS_5C: dc.b $4
	dc.b $F8, $F, $0, $0, $EC
	dc.b $E8, $1, $0, $10, $4
	dc.b $F8, $4, $0, $12, $C
	dc.b $0, $0, $0, $14, $C
DATARSKSYXXHDS_5D: dc.b $4
	dc.b $F0, $E, $0, $0, $ED
	dc.b $E8, $4, $0, $C, $FD
	dc.b $8, $C, $0, $E, $FD
	dc.b $10, $0, $0, $12, $5
	even