; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 19 2021 12:34:29 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAK86LWJFDRWE:
	dc.w $0, DATAK86LWJFDRWE_1-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_2-DATAK86LWJFDRWE, DATAK86LWJFDRWE_3-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_4-DATAK86LWJFDRWE, DATAK86LWJFDRWE_5-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_6-DATAK86LWJFDRWE, DATAK86LWJFDRWE_7-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_8-DATAK86LWJFDRWE, DATAK86LWJFDRWE_9-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_A-DATAK86LWJFDRWE, DATAK86LWJFDRWE_B-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_C-DATAK86LWJFDRWE, DATAK86LWJFDRWE_D-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_E-DATAK86LWJFDRWE, DATAK86LWJFDRWE_F-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_10-DATAK86LWJFDRWE, DATAK86LWJFDRWE_11-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_12-DATAK86LWJFDRWE, DATAK86LWJFDRWE_13-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_14-DATAK86LWJFDRWE, DATAK86LWJFDRWE_15-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_16-DATAK86LWJFDRWE, DATAK86LWJFDRWE_17-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_18-DATAK86LWJFDRWE, DATAK86LWJFDRWE_19-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_1A-DATAK86LWJFDRWE, DATAK86LWJFDRWE_1B-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_1C-DATAK86LWJFDRWE, DATAK86LWJFDRWE_1D-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_1E-DATAK86LWJFDRWE, DATAK86LWJFDRWE_1F-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_20-DATAK86LWJFDRWE, DATAK86LWJFDRWE_21-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_22-DATAK86LWJFDRWE, DATAK86LWJFDRWE_23-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_24-DATAK86LWJFDRWE, DATAK86LWJFDRWE_25-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_26-DATAK86LWJFDRWE, DATAK86LWJFDRWE_27-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_28-DATAK86LWJFDRWE, DATAK86LWJFDRWE_29-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_2A-DATAK86LWJFDRWE, DATAK86LWJFDRWE_2B-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_2C-DATAK86LWJFDRWE, DATAK86LWJFDRWE_2D-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_2E-DATAK86LWJFDRWE, DATAK86LWJFDRWE_2F-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_30-DATAK86LWJFDRWE, DATAK86LWJFDRWE_31-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_32-DATAK86LWJFDRWE, DATAK86LWJFDRWE_33-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_34-DATAK86LWJFDRWE, DATAK86LWJFDRWE_35-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_36-DATAK86LWJFDRWE, DATAK86LWJFDRWE_37-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_38-DATAK86LWJFDRWE, DATAK86LWJFDRWE_39-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_3A-DATAK86LWJFDRWE, DATAK86LWJFDRWE_3B-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_3C-DATAK86LWJFDRWE, DATAK86LWJFDRWE_3D-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_3E-DATAK86LWJFDRWE, DATAK86LWJFDRWE_3F-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_40-DATAK86LWJFDRWE, DATAK86LWJFDRWE_41-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_42-DATAK86LWJFDRWE, DATAK86LWJFDRWE_43-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_44-DATAK86LWJFDRWE, DATAK86LWJFDRWE_45-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_46-DATAK86LWJFDRWE, DATAK86LWJFDRWE_47-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_48-DATAK86LWJFDRWE, $0
	dc.w $0, $0
	dc.w DATAK86LWJFDRWE_4C-DATAK86LWJFDRWE, DATAK86LWJFDRWE_4D-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_4E-DATAK86LWJFDRWE, DATAK86LWJFDRWE_4F-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_50-DATAK86LWJFDRWE, DATAK86LWJFDRWE_51-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_52-DATAK86LWJFDRWE, DATAK86LWJFDRWE_53-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_54-DATAK86LWJFDRWE, DATAK86LWJFDRWE_55-DATAK86LWJFDRWE
	dc.w DATAK86LWJFDRWE_56-DATAK86LWJFDRWE, DATAK86LWJFDRWE_57-DATAK86LWJFDRWE
DATAK86LWJFDRWE_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_3: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_4: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_6: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAK86LWJFDRWE_7: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAK86LWJFDRWE_8: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAK86LWJFDRWE_9: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAK86LWJFDRWE_A: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAK86LWJFDRWE_B: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAK86LWJFDRWE_C: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAK86LWJFDRWE_D: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAK86LWJFDRWE_E: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAK86LWJFDRWE_F: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAK86LWJFDRWE_10: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAK86LWJFDRWE_11: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAK86LWJFDRWE_12: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAK86LWJFDRWE_13: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAK86LWJFDRWE_14: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAK86LWJFDRWE_15: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAK86LWJFDRWE_16: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAK86LWJFDRWE_17: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAK86LWJFDRWE_18: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAK86LWJFDRWE_19: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAK86LWJFDRWE_1A: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAK86LWJFDRWE_1B: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAK86LWJFDRWE_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAK86LWJFDRWE_1D: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAK86LWJFDRWE_1E: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAK86LWJFDRWE_1F: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAK86LWJFDRWE_20: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAK86LWJFDRWE_21: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAK86LWJFDRWE_22: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAK86LWJFDRWE_23: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAK86LWJFDRWE_24: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAK86LWJFDRWE_25: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAK86LWJFDRWE_26: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $4, $0, $C, $6
	dc.b $F0, $0, $0, $E, $E
DATAK86LWJFDRWE_27: dc.b $2
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $5, $0, $9, $5
DATAK86LWJFDRWE_28: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $4, $0, $C, $5
	dc.b $F0, $0, $0, $E, $D
DATAK86LWJFDRWE_29: dc.b $2
	dc.b $EF, $A, $0, $0, $EC
	dc.b $F7, $5, $0, $9, $4
DATAK86LWJFDRWE_2A: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAK86LWJFDRWE_2B: dc.b $3
	dc.b $0, $A, $0, $0, $E4
	dc.b $F0, $5, $0, $9, $FC
	dc.b $0, $1, $0, $D, $FC
DATAK86LWJFDRWE_2C: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAK86LWJFDRWE_2D: dc.b $3
	dc.b $0, $A, $0, $0, $E3
	dc.b $F0, $5, $0, $9, $FB
	dc.b $0, $1, $0, $D, $FB
DATAK86LWJFDRWE_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAK86LWJFDRWE_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAK86LWJFDRWE_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAK86LWJFDRWE_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAK86LWJFDRWE_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAK86LWJFDRWE_33: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAK86LWJFDRWE_34: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAK86LWJFDRWE_35: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAK86LWJFDRWE_36: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAK86LWJFDRWE_37: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_38: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK86LWJFDRWE_39: dc.b $1
	dc.b $F9, $B, $0, $0, $F4
DATAK86LWJFDRWE_3A: dc.b $2
	dc.b $EC, $B, $0, $0, $EE
	dc.b $C, $8, $0, $C, $EE
DATAK86LWJFDRWE_3B: dc.b $2
	dc.b $ED, $B, $0, $0, $EB
	dc.b $D, $8, $0, $C, $EB
DATAK86LWJFDRWE_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAK86LWJFDRWE_3D: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAK86LWJFDRWE_3E: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAK86LWJFDRWE_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAK86LWJFDRWE_40: dc.b $4
	dc.b $10, $4, $0, $0, $EC
	dc.b $F0, $B, $0, $2, $F4
	dc.b $E8, $4, $0, $E, $FC
	dc.b $10, $0, $0, $10, $4
DATAK86LWJFDRWE_41: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAK86LWJFDRWE_42: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAK86LWJFDRWE_43: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAK86LWJFDRWE_44: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAK86LWJFDRWE_45: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAK86LWJFDRWE_46: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAK86LWJFDRWE_47: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAK86LWJFDRWE_48: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAK86LWJFDRWE_4C: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAK86LWJFDRWE_4D: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAK86LWJFDRWE_4E: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAK86LWJFDRWE_4F: dc.b $2
	dc.b $F0, $D, $0, $0, $F0
	dc.b $0, $5, $0, $8, $F8
DATAK86LWJFDRWE_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAK86LWJFDRWE_51: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAK86LWJFDRWE_52: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAK86LWJFDRWE_53: dc.b $2
	dc.b $F4, $A, $8, $0, $E8
	dc.b $FC, $8, $8, $9, $0
DATAK86LWJFDRWE_54: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAK86LWJFDRWE_55: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $FC, $0, $0, $10, $EA
	dc.b $C, $8, $0, $11, $FA
DATAK86LWJFDRWE_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $1, $0, $E, $C
	dc.b $C, $C, $0, $10, $EC
DATAK86LWJFDRWE_57: dc.b $4
	dc.b $EE, $B, $0, $0, $F4
	dc.b $F6, $1, $0, $C, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $4, $0, $11, $FC
	even