; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Aug 13 2021 22:36:15 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATARS050VX4O2:
	dc.w $0, DATARS050VX4O2_1-DATARS050VX4O2
	dc.w DATARS050VX4O2_2-DATARS050VX4O2, DATARS050VX4O2_3-DATARS050VX4O2
	dc.w DATARS050VX4O2_4-DATARS050VX4O2, DATARS050VX4O2_5-DATARS050VX4O2
	dc.w DATARS050VX4O2_6-DATARS050VX4O2, DATARS050VX4O2_7-DATARS050VX4O2
	dc.w DATARS050VX4O2_8-DATARS050VX4O2, DATARS050VX4O2_9-DATARS050VX4O2
	dc.w DATARS050VX4O2_A-DATARS050VX4O2, DATARS050VX4O2_B-DATARS050VX4O2
	dc.w DATARS050VX4O2_C-DATARS050VX4O2, DATARS050VX4O2_D-DATARS050VX4O2
	dc.w DATARS050VX4O2_E-DATARS050VX4O2, DATARS050VX4O2_F-DATARS050VX4O2
	dc.w DATARS050VX4O2_10-DATARS050VX4O2, DATARS050VX4O2_11-DATARS050VX4O2
	dc.w DATARS050VX4O2_12-DATARS050VX4O2, DATARS050VX4O2_13-DATARS050VX4O2
	dc.w DATARS050VX4O2_14-DATARS050VX4O2, DATARS050VX4O2_15-DATARS050VX4O2
	dc.w DATARS050VX4O2_16-DATARS050VX4O2, DATARS050VX4O2_17-DATARS050VX4O2
	dc.w DATARS050VX4O2_18-DATARS050VX4O2, DATARS050VX4O2_19-DATARS050VX4O2
	dc.w DATARS050VX4O2_1A-DATARS050VX4O2, DATARS050VX4O2_1B-DATARS050VX4O2
	dc.w DATARS050VX4O2_1C-DATARS050VX4O2, DATARS050VX4O2_1D-DATARS050VX4O2
	dc.w DATARS050VX4O2_1E-DATARS050VX4O2, DATARS050VX4O2_1F-DATARS050VX4O2
	dc.w DATARS050VX4O2_20-DATARS050VX4O2, DATARS050VX4O2_21-DATARS050VX4O2
	dc.w DATARS050VX4O2_22-DATARS050VX4O2, DATARS050VX4O2_23-DATARS050VX4O2
	dc.w DATARS050VX4O2_24-DATARS050VX4O2, DATARS050VX4O2_25-DATARS050VX4O2
	dc.w DATARS050VX4O2_26-DATARS050VX4O2, DATARS050VX4O2_27-DATARS050VX4O2
	dc.w DATARS050VX4O2_28-DATARS050VX4O2, DATARS050VX4O2_29-DATARS050VX4O2
	dc.w DATARS050VX4O2_2A-DATARS050VX4O2, DATARS050VX4O2_2B-DATARS050VX4O2
	dc.w DATARS050VX4O2_2C-DATARS050VX4O2, DATARS050VX4O2_2D-DATARS050VX4O2
	dc.w DATARS050VX4O2_2E-DATARS050VX4O2, DATARS050VX4O2_2F-DATARS050VX4O2
	dc.w DATARS050VX4O2_30-DATARS050VX4O2, DATARS050VX4O2_31-DATARS050VX4O2
	dc.w DATARS050VX4O2_32-DATARS050VX4O2, DATARS050VX4O2_33-DATARS050VX4O2
	dc.w DATARS050VX4O2_34-DATARS050VX4O2, DATARS050VX4O2_35-DATARS050VX4O2
	dc.w DATARS050VX4O2_36-DATARS050VX4O2, DATARS050VX4O2_37-DATARS050VX4O2
	dc.w DATARS050VX4O2_38-DATARS050VX4O2, DATARS050VX4O2_39-DATARS050VX4O2
	dc.w DATARS050VX4O2_3A-DATARS050VX4O2, DATARS050VX4O2_3B-DATARS050VX4O2
	dc.w DATARS050VX4O2_3C-DATARS050VX4O2, DATARS050VX4O2_3D-DATARS050VX4O2
	dc.w DATARS050VX4O2_3E-DATARS050VX4O2, DATARS050VX4O2_3F-DATARS050VX4O2
	dc.w DATARS050VX4O2_40-DATARS050VX4O2, DATARS050VX4O2_41-DATARS050VX4O2
	dc.w DATARS050VX4O2_42-DATARS050VX4O2, DATARS050VX4O2_43-DATARS050VX4O2
	dc.w DATARS050VX4O2_44-DATARS050VX4O2, DATARS050VX4O2_45-DATARS050VX4O2
	dc.w DATARS050VX4O2_46-DATARS050VX4O2, DATARS050VX4O2_47-DATARS050VX4O2
	dc.w DATARS050VX4O2_48-DATARS050VX4O2, $0
	dc.w $0, $0
	dc.w DATARS050VX4O2_4C-DATARS050VX4O2, DATARS050VX4O2_4D-DATARS050VX4O2
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATARS050VX4O2_53-DATARS050VX4O2
	dc.w DATARS050VX4O2_54-DATARS050VX4O2, DATARS050VX4O2_55-DATARS050VX4O2
	dc.w DATARS050VX4O2_56-DATARS050VX4O2, DATARS050VX4O2_57-DATARS050VX4O2
	dc.w DATARS050VX4O2_58-DATARS050VX4O2, DATARS050VX4O2_59-DATARS050VX4O2
	dc.w DATARS050VX4O2_5A-DATARS050VX4O2, DATARS050VX4O2_5B-DATARS050VX4O2
	dc.w DATARS050VX4O2_5C-DATARS050VX4O2, DATARS050VX4O2_5D-DATARS050VX4O2
DATARS050VX4O2_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_3: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_4: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_6: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATARS050VX4O2_7: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATARS050VX4O2_8: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATARS050VX4O2_9: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATARS050VX4O2_A: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATARS050VX4O2_B: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATARS050VX4O2_C: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATARS050VX4O2_D: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATARS050VX4O2_E: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATARS050VX4O2_F: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATARS050VX4O2_10: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATARS050VX4O2_11: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATARS050VX4O2_12: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATARS050VX4O2_13: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATARS050VX4O2_14: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATARS050VX4O2_15: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATARS050VX4O2_16: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATARS050VX4O2_17: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATARS050VX4O2_18: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATARS050VX4O2_19: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATARS050VX4O2_1A: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATARS050VX4O2_1B: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATARS050VX4O2_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATARS050VX4O2_1D: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATARS050VX4O2_1E: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATARS050VX4O2_1F: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATARS050VX4O2_20: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATARS050VX4O2_21: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATARS050VX4O2_22: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATARS050VX4O2_23: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATARS050VX4O2_24: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATARS050VX4O2_25: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATARS050VX4O2_26: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $4, $0, $C, $6
	dc.b $F0, $0, $0, $E, $E
DATARS050VX4O2_27: dc.b $2
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $5, $0, $9, $5
DATARS050VX4O2_28: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $4, $0, $C, $5
	dc.b $F0, $0, $0, $E, $D
DATARS050VX4O2_29: dc.b $2
	dc.b $EF, $A, $0, $0, $EC
	dc.b $F7, $5, $0, $9, $4
DATARS050VX4O2_2A: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATARS050VX4O2_2B: dc.b $3
	dc.b $0, $A, $0, $0, $E4
	dc.b $F0, $5, $0, $9, $FC
	dc.b $0, $1, $0, $D, $FC
DATARS050VX4O2_2C: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATARS050VX4O2_2D: dc.b $3
	dc.b $0, $A, $0, $0, $E3
	dc.b $F0, $5, $0, $9, $FB
	dc.b $0, $1, $0, $D, $FB
DATARS050VX4O2_2E: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_2F: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_30: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_31: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_32: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_33: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_34: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_35: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_36: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATARS050VX4O2_37: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_38: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARS050VX4O2_39: dc.b $1
	dc.b $F9, $B, $0, $0, $F4
DATARS050VX4O2_3A: dc.b $2
	dc.b $EC, $B, $0, $0, $EE
	dc.b $C, $8, $0, $C, $EE
DATARS050VX4O2_3B: dc.b $2
	dc.b $ED, $B, $0, $0, $EB
	dc.b $D, $8, $0, $C, $EB
DATARS050VX4O2_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATARS050VX4O2_3D: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARS050VX4O2_3E: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARS050VX4O2_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATARS050VX4O2_40: dc.b $4
	dc.b $10, $4, $0, $0, $EC
	dc.b $F0, $B, $0, $2, $F4
	dc.b $E8, $4, $0, $E, $FC
	dc.b $10, $0, $0, $10, $4
DATARS050VX4O2_41: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATARS050VX4O2_42: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATARS050VX4O2_43: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATARS050VX4O2_44: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATARS050VX4O2_45: dc.b $3
	dc.b $EC, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FC, $1, $0, $E, $5
DATARS050VX4O2_46: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATARS050VX4O2_47: dc.b $3
	dc.b $EC, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FC, $1, $0, $E, $5
DATARS050VX4O2_48: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATARS050VX4O2_4C: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATARS050VX4O2_4D: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATARS050VX4O2_53: dc.b $2
	dc.b $F4, $A, $8, $0, $E8
	dc.b $FC, $8, $8, $9, $0
DATARS050VX4O2_54: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATARS050VX4O2_55: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $FC, $0, $0, $10, $EA
	dc.b $C, $8, $0, $11, $FA
DATARS050VX4O2_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $1, $0, $E, $C
	dc.b $C, $C, $0, $10, $EC
DATARS050VX4O2_57: dc.b $4
	dc.b $EE, $B, $0, $0, $F4
	dc.b $F6, $1, $0, $C, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $4, $0, $11, $FC
DATARS050VX4O2_58: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $E8, $4, $0, $8, $F4
	dc.b $0, $A, $0, $A, $F4
	dc.b $F0, $1, $0, $13, $C
DATARS050VX4O2_59: dc.b $4
	dc.b $EE, $F, $0, $0, $F4
	dc.b $FE, $1, $0, $10, $14
	dc.b $6, $0, $0, $12, $EC
	dc.b $E, $1, $0, $13, $F4
DATARS050VX4O2_5A: dc.b $4
	dc.b $F5, $C, $0, $0, $E4
	dc.b $ED, $0, $0, $4, $F4
	dc.b $FD, $E, $0, $5, $F4
	dc.b $15, $4, $0, $11, $F4
DATARS050VX4O2_5B: dc.b $4
	dc.b $7, $D, $0, $0, $EC
	dc.b $EF, $A, $0, $8, $F4
	dc.b $17, $4, $0, $11, $FC
	dc.b $7, $1, $0, $13, $C
DATARS050VX4O2_5C: dc.b $4
	dc.b $F8, $F, $0, $0, $EC
	dc.b $E8, $1, $0, $10, $4
	dc.b $F8, $4, $0, $12, $C
	dc.b $0, $0, $0, $14, $C
DATARS050VX4O2_5D: dc.b $4
	dc.b $F0, $E, $0, $0, $ED
	dc.b $E8, $4, $0, $C, $FD
	dc.b $8, $C, $0, $E, $FD
	dc.b $10, $0, $0, $12, $5
	even