; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 10 2021 21:29:34 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAA2ZE0USOWXG:
	dc.w DATAA2ZE0USOWXG_0-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_1-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_2-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_3-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_4-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_5-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_6-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_7-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_8-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_9-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_A-DATAA2ZE0USOWXG, DATAA2ZE0USOWXG_B-DATAA2ZE0USOWXG
	dc.w DATAA2ZE0USOWXG_C-DATAA2ZE0USOWXG
DATAA2ZE0USOWXG_0: dc.b $6
	dc.b $EC, $1, $0, $A, $E4
	dc.b $EC, $5, $0, $C, $C
	dc.b $FC, $E, $20, $10, $E4
	dc.b $FC, $E, $20, $1C, $4
	dc.b $14, $C, $20, $28, $EC
	dc.b $14, $0, $20, $2C, $C
DATAA2ZE0USOWXG_1: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $2, $EC
DATAA2ZE0USOWXG_2: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATAA2ZE0USOWXG_3: dc.b $3
	dc.b $E4, $8, $0, $3D, $F4
	dc.b $EC, $9, $0, $40, $EC
	dc.b $EC, $5, $0, $46, $4
DATAA2ZE0USOWXG_4: dc.b $3
	dc.b $E4, $8, $0, $4A, $F4
	dc.b $EC, $9, $0, $4D, $EC
	dc.b $EC, $5, $0, $53, $4
DATAA2ZE0USOWXG_5: dc.b $3
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATAA2ZE0USOWXG_6: dc.b $3
	dc.b $E4, $4, $0, $64, $4
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATAA2ZE0USOWXG_7: dc.b $4
	dc.b $E4, $9, $0, $66, $F4
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATAA2ZE0USOWXG_8: dc.b $1
	dc.b $4, $5, $0, $2D, $22
DATAA2ZE0USOWXG_9: dc.b $1
	dc.b $4, $5, $0, $31, $22
DATAA2ZE0USOWXG_A: dc.b $0
DATAA2ZE0USOWXG_B: dc.b $2
	dc.b $0, $8, $1, $2A, $22
	dc.b $8, $8, $11, $2A, $22
DATAA2ZE0USOWXG_C: dc.b $2
	dc.b $F8, $B, $1, $2D, $22
	dc.b $0, $1, $1, $39, $3A
	even