; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 11 2021 10:29:07 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA2015R89ZOREI:
	dc.w DATA2015R89ZOREI_0-DATA2015R89ZOREI, DATA2015R89ZOREI_1-DATA2015R89ZOREI
	dc.w DATA2015R89ZOREI_2-DATA2015R89ZOREI, DATA2015R89ZOREI_3-DATA2015R89ZOREI
	dc.w DATA2015R89ZOREI_4-DATA2015R89ZOREI, DATA2015R89ZOREI_5-DATA2015R89ZOREI
	dc.w DATA2015R89ZOREI_6-DATA2015R89ZOREI
DATA2015R89ZOREI_0: dc.b $2
	dc.b $EC, $F, $0, $5A, $F0
	dc.b $C, $8, $0, $6A, $F8
DATA2015R89ZOREI_1: dc.b $2
	dc.b $EC, $A, $0, $F, $F0
	dc.b $4, $9, $0, $18, $F4
DATA2015R89ZOREI_2: dc.b $2
	dc.b $E8, $A, $0, $1E, $F4
	dc.b $0, $A, $0, $27, $F4
DATA2015R89ZOREI_3: dc.b $2
	dc.b $E8, $A, $0, $30, $F4
	dc.b $0, $A, $0, $39, $F4
DATA2015R89ZOREI_4: dc.b $2
	dc.b $E8, $A, $0, $F, $F0
	dc.b $0, $A, $0, $42, $F4
DATA2015R89ZOREI_5: dc.b $2
	dc.b $F4, $6, $0, $4B, $E8
	dc.b $F4, $A, $0, $51, $F8
DATA2015R89ZOREI_6: dc.b $2
	dc.b $EC, $A, $0, $F, $F0
	dc.b $4, $9, $0, $9, $F4
	even