; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Aug 13 2021 18:28:18 GMT+0100 (GMT Summer Time)
; ================================================================================

DATALWL9EXWUKM:
	dc.w DATALWL9EXWUKM_0-DATALWL9EXWUKM, DATALWL9EXWUKM_1-DATALWL9EXWUKM
	dc.w DATALWL9EXWUKM_2-DATALWL9EXWUKM, DATALWL9EXWUKM_3-DATALWL9EXWUKM
	dc.w DATALWL9EXWUKM_4-DATALWL9EXWUKM, DATALWL9EXWUKM_5-DATALWL9EXWUKM
	dc.w DATALWL9EXWUKM_6-DATALWL9EXWUKM, DATALWL9EXWUKM_7-DATALWL9EXWUKM
DATALWL9EXWUKM_0: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_1: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_2: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_3: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_4: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_5: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
DATALWL9EXWUKM_6: dc.b $3
	dc.b $EC, $F, $0, $1A, $F4
	dc.b $F4, $6, $0, $2A, $E4
	dc.b $C, $C, $0, $30, $F4
DATALWL9EXWUKM_7: dc.b $3
	dc.b $F8, $F, $8, $0, $F3
	dc.b $E8, $9, $8, $10, $F3
	dc.b $F8, $3, $8, $16, $EB
	even