; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 18 2020 19:46:36 GMT+0100 (GMT Summer Time)
; ================================================================================

DATA7TKC1WYEKR:
	dc.w DATA7TKC1WYEKR_0-DATA7TKC1WYEKR, DATA7TKC1WYEKR_1-DATA7TKC1WYEKR
	dc.w DATA7TKC1WYEKR_2-DATA7TKC1WYEKR, DATA7TKC1WYEKR_3-DATA7TKC1WYEKR
	dc.w DATA7TKC1WYEKR_4-DATA7TKC1WYEKR, DATA7TKC1WYEKR_5-DATA7TKC1WYEKR
	dc.w DATA7TKC1WYEKR_6-DATA7TKC1WYEKR
DATA7TKC1WYEKR_0: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $0, $C, $0, $8, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $8, $0, $E, $F4
DATA7TKC1WYEKR_1: dc.b $4
	dc.b $F1, $D, $0, $0, $EC
	dc.b $1, $C, $0, $8, $EC
	dc.b $F9, $1, $0, $C, $C
	dc.b $9, $8, $0, $11, $F4
DATA7TKC1WYEKR_2: dc.b $5
	dc.b $F0, $D, $0, $0, $EC
	dc.b $0, $C, $0, $14, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $4, $0, $18, $EC
	dc.b $8, $4, $0, $12, $FC
DATA7TKC1WYEKR_3: dc.b $1
	dc.b $FA, $0, $0, $1A, $10
DATA7TKC1WYEKR_4: dc.b $1
	dc.b $FA, $0, $0, $1B, $10
DATA7TKC1WYEKR_5: dc.b $1
	dc.b $FA, $0, $0, $1C, $10
DATA7TKC1WYEKR_6: dc.b $0
	even