; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Sep 08 2021 15:09:30 GMT+0100 (GMT Summer Time)
; ================================================================================

DATA1NPYREXM2KC:
	dc.w DATA1NPYREXM2KC_0-DATA1NPYREXM2KC, DATA1NPYREXM2KC_1-DATA1NPYREXM2KC
	dc.w DATA1NPYREXM2KC_2-DATA1NPYREXM2KC, DATA1NPYREXM2KC_3-DATA1NPYREXM2KC
	dc.w DATA1NPYREXM2KC_4-DATA1NPYREXM2KC, DATA1NPYREXM2KC_5-DATA1NPYREXM2KC
	dc.w DATA1NPYREXM2KC_6-DATA1NPYREXM2KC, DATA1NPYREXM2KC_7-DATA1NPYREXM2KC
DATA1NPYREXM2KC_0: dc.b $2
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATA1NPYREXM2KC_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATA1NPYREXM2KC_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATA1NPYREXM2KC_3: dc.b $2
	dc.b $EC, $9, $0, $10, $F8
	dc.b $FC, $E, $0, $16, $F0
DATA1NPYREXM2KC_4: dc.b $2
	dc.b $EC, $9, $8, $10, $F0
	dc.b $FC, $E, $8, $16, $F0
DATA1NPYREXM2KC_5: dc.b $3
	dc.b $EC, $6, $0, $22, $F0
	dc.b $EC, $6, $8, $22, $0
	dc.b $4, $D, $0, $28, $F0
DATA1NPYREXM2KC_6: dc.b $3
	dc.b $EC, $6, $0, $22, $F0
	dc.b $EC, $6, $8, $22, $0
	dc.b $4, $D, $0, $28, $F0
DATA1NPYREXM2KC_7: dc.b $23
	dc.b $A1, $F, $0, $30, $E6
	dc.b $A1, $F, $0, $40, $6
	dc.b $A9, $7, $0, $50, $D6
	dc.b $A9, $B, $0, $58, $26
	dc.b $B1, $7, $0, $64, $C6
	dc.b $B1, $1, $0, $6C, $3E
	dc.b $C1, $F, $0, $6E, $E6
	dc.b $C1, $F, $0, $7E, $6
	dc.b $C9, $7, $0, $8E, $D6
	dc.b $C9, $D, $0, $96, $26
	dc.b $D1, $4, $0, $9E, $C6
	dc.b $D9, $7, $0, $A0, $26
	dc.b $E1, $F, $0, $A8, $B6
	dc.b $E1, $F, $0, $B8, $E6
	dc.b $E1, $F, $0, $C8, $6
	dc.b $E1, $B, $0, $D8, $36
	dc.b $E9, $3, $0, $E4, $AE
	dc.b $E9, $7, $0, $E8, $D6
	dc.b $E9, $7, $0, $F0, $4E
	dc.b $F1, $6, $0, $F8, $9E
	dc.b $F1, $6, $0, $FE, $5E
	dc.b $F9, $0, $1, $4, $96
	dc.b $F9, $7, $1, $5, $26
	dc.b $1, $C, $1, $D, $B6
	dc.b $1, $D, $1, $11, $E6
	dc.b $1, $F, $1, $19, $6
	dc.b $1, $8, $1, $29, $36
	dc.b $9, $F, $1, $2C, $C6
	dc.b $9, $3, $1, $3C, $36
	dc.b $11, $6, $1, $40, $E6
	dc.b $19, $6, $1, $46, $B6
	dc.b $19, $5, $1, $4C, $26
	dc.b $19, $5, $1, $50, $3E
	dc.b $21, $C, $1, $54, $6
	dc.b $29, $C, $1, $58, $C6
	even