; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 11 2021 12:27:16 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAP0GAP5LACHB:
	dc.w $0, DATAP0GAP5LACHB_1-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_2-DATAP0GAP5LACHB, DATAP0GAP5LACHB_3-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_4-DATAP0GAP5LACHB, DATAP0GAP5LACHB_5-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_6-DATAP0GAP5LACHB, DATAP0GAP5LACHB_7-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_8-DATAP0GAP5LACHB, DATAP0GAP5LACHB_9-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_A-DATAP0GAP5LACHB, DATAP0GAP5LACHB_B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_D-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_E-DATAP0GAP5LACHB, DATAP0GAP5LACHB_F-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_10-DATAP0GAP5LACHB, DATAP0GAP5LACHB_11-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_12-DATAP0GAP5LACHB, DATAP0GAP5LACHB_13-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_14-DATAP0GAP5LACHB, DATAP0GAP5LACHB_15-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_16-DATAP0GAP5LACHB, DATAP0GAP5LACHB_17-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_18-DATAP0GAP5LACHB, DATAP0GAP5LACHB_19-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_1A-DATAP0GAP5LACHB, DATAP0GAP5LACHB_1B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_1C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_1D-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_1E-DATAP0GAP5LACHB, DATAP0GAP5LACHB_1F-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_20-DATAP0GAP5LACHB, DATAP0GAP5LACHB_21-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_22-DATAP0GAP5LACHB, DATAP0GAP5LACHB_23-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_24-DATAP0GAP5LACHB, DATAP0GAP5LACHB_25-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_26-DATAP0GAP5LACHB, DATAP0GAP5LACHB_27-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_28-DATAP0GAP5LACHB, DATAP0GAP5LACHB_29-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_2A-DATAP0GAP5LACHB, DATAP0GAP5LACHB_2B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_2C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_2D-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_2E-DATAP0GAP5LACHB, DATAP0GAP5LACHB_2F-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_30-DATAP0GAP5LACHB, DATAP0GAP5LACHB_31-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_32-DATAP0GAP5LACHB, $0
	dc.w $0, $0
	dc.w $0, DATAP0GAP5LACHB_37-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_38-DATAP0GAP5LACHB, DATAP0GAP5LACHB_39-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_3A-DATAP0GAP5LACHB, DATAP0GAP5LACHB_3B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_3C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_3D-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_3E-DATAP0GAP5LACHB, DATAP0GAP5LACHB_3F-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_40-DATAP0GAP5LACHB, DATAP0GAP5LACHB_41-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_42-DATAP0GAP5LACHB, $0
	dc.w $0, DATAP0GAP5LACHB_45-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_46-DATAP0GAP5LACHB, DATAP0GAP5LACHB_47-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_48-DATAP0GAP5LACHB, DATAP0GAP5LACHB_49-DATAP0GAP5LACHB
	dc.w $0, DATAP0GAP5LACHB_4B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_4C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_4D-DATAP0GAP5LACHB
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAP0GAP5LACHB_53-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_54-DATAP0GAP5LACHB, DATAP0GAP5LACHB_55-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_56-DATAP0GAP5LACHB, DATAP0GAP5LACHB_57-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_58-DATAP0GAP5LACHB, DATAP0GAP5LACHB_59-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_5A-DATAP0GAP5LACHB, DATAP0GAP5LACHB_5B-DATAP0GAP5LACHB
	dc.w DATAP0GAP5LACHB_5C-DATAP0GAP5LACHB, DATAP0GAP5LACHB_5D-DATAP0GAP5LACHB
DATAP0GAP5LACHB_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAP0GAP5LACHB_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAP0GAP5LACHB_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAP0GAP5LACHB_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAP0GAP5LACHB_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAP0GAP5LACHB_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAP0GAP5LACHB_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAP0GAP5LACHB_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAP0GAP5LACHB_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAP0GAP5LACHB_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAP0GAP5LACHB_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAP0GAP5LACHB_C: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $6, $0, $9, $F3
	dc.b $FA, $8, $0, $F, $3
	dc.b $F2, $4, $0, $12, $B
DATAP0GAP5LACHB_D: dc.b $5
	dc.b $EA, $A, $0, $0, $EE
	dc.b $F2, $0, $0, $9, $E6
	dc.b $FA, $5, $0, $A, $6
	dc.b $2, $5, $0, $E, $F6
	dc.b $12, $0, $0, $12, $FE
DATAP0GAP5LACHB_E: dc.b $5
	dc.b $F8, $C, $0, $0, $E4
	dc.b $E8, $9, $0, $4, $EC
	dc.b $0, $8, $0, $A, $F4
	dc.b $8, $8, $0, $D, $FC
	dc.b $F8, $0, $0, $10, $4
DATAP0GAP5LACHB_F: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $6, $0, $9, $F3
	dc.b $FA, $8, $0, $F, $3
	dc.b $F2, $4, $0, $12, $B
DATAP0GAP5LACHB_10: dc.b $5
	dc.b $EA, $A, $0, $0, $EE
	dc.b $F2, $0, $0, $9, $E6
	dc.b $FA, $5, $0, $A, $6
	dc.b $2, $5, $0, $E, $F6
	dc.b $12, $0, $0, $12, $FE
DATAP0GAP5LACHB_11: dc.b $4
	dc.b $E9, $A, $0, $0, $EC
	dc.b $1, $8, $0, $9, $F4
	dc.b $9, $8, $0, $C, $FC
	dc.b $F9, $0, $0, $F, $4
DATAP0GAP5LACHB_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAP0GAP5LACHB_13: dc.b $5
	dc.b $F2, $3, $0, $0, $F7
	dc.b $F2, $3, $0, $4, $F
	dc.b $FA, $5, $0, $8, $E7
	dc.b $FA, $6, $0, $C, $FF
	dc.b $A, $0, $0, $12, $EF
DATAP0GAP5LACHB_14: dc.b $4
	dc.b $F9, $E, $0, $0, $ED
	dc.b $11, $0, $0, $C, $F5
	dc.b $F9, $2, $0, $D, $D
	dc.b $1, $1, $0, $10, $15
DATAP0GAP5LACHB_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAP0GAP5LACHB_16: dc.b $5
	dc.b $F2, $3, $0, $0, $F7
	dc.b $F2, $3, $0, $4, $F
	dc.b $FA, $5, $0, $8, $E7
	dc.b $FA, $6, $0, $C, $FF
	dc.b $A, $0, $0, $12, $EF
DATAP0GAP5LACHB_17: dc.b $4
	dc.b $F9, $E, $0, $0, $ED
	dc.b $11, $0, $0, $C, $F5
	dc.b $F9, $2, $0, $D, $D
	dc.b $1, $1, $0, $10, $15
DATAP0GAP5LACHB_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAP0GAP5LACHB_19: dc.b $5
	dc.b $FD, $A, $0, $0, $EA
	dc.b $15, $0, $0, $9, $F2
	dc.b $ED, $5, $0, $A, $FA
	dc.b $FD, $5, $0, $E, $2
	dc.b $FD, $0, $0, $12, $12
DATAP0GAP5LACHB_1A: dc.b $4
	dc.b $EF, $2, $0, $0, $8
	dc.b $F7, $6, $0, $3, $F8
	dc.b $FF, $6, $0, $9, $E8
	dc.b $F, $1, $0, $F, $F8
DATAP0GAP5LACHB_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAP0GAP5LACHB_1C: dc.b $5
	dc.b $FD, $A, $0, $0, $EA
	dc.b $15, $0, $0, $9, $F2
	dc.b $ED, $5, $0, $A, $FA
	dc.b $FD, $5, $0, $E, $2
	dc.b $FD, $0, $0, $12, $12
DATAP0GAP5LACHB_1D: dc.b $4
	dc.b $F0, $2, $0, $0, $9
	dc.b $F8, $6, $0, $3, $F9
	dc.b $0, $6, $0, $9, $E9
	dc.b $10, $0, $0, $F, $F9
DATAP0GAP5LACHB_1E: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAP0GAP5LACHB_1F: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAP0GAP5LACHB_20: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAP0GAP5LACHB_21: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAP0GAP5LACHB_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAP0GAP5LACHB_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAP0GAP5LACHB_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAP0GAP5LACHB_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAP0GAP5LACHB_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAP0GAP5LACHB_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAP0GAP5LACHB_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAP0GAP5LACHB_29: dc.b $4
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $0, $0, $C, $F4
	dc.b $EE, $4, $0, $D, $4
	dc.b $F6, $1, $0, $F, $C
DATAP0GAP5LACHB_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAP0GAP5LACHB_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAP0GAP5LACHB_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAP0GAP5LACHB_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAP0GAP5LACHB_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAP0GAP5LACHB_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAP0GAP5LACHB_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAP0GAP5LACHB_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAP0GAP5LACHB_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAP0GAP5LACHB_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAP0GAP5LACHB_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAP0GAP5LACHB_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATAP0GAP5LACHB_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAP0GAP5LACHB_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAP0GAP5LACHB_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAP0GAP5LACHB_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAP0GAP5LACHB_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAP0GAP5LACHB_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAP0GAP5LACHB_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAP0GAP5LACHB_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAP0GAP5LACHB_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAP0GAP5LACHB_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATAP0GAP5LACHB_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAP0GAP5LACHB_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATAP0GAP5LACHB_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAP0GAP5LACHB_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAP0GAP5LACHB_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAP0GAP5LACHB_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAP0GAP5LACHB_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAP0GAP5LACHB_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAP0GAP5LACHB_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAP0GAP5LACHB_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAP0GAP5LACHB_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAP0GAP5LACHB_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAP0GAP5LACHB_58: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $8, $0, $C, $F6
	dc.b $F9, $1, $0, $F, $E
DATAP0GAP5LACHB_59: dc.b $2
	dc.b $F1, $F, $0, $0, $F0
	dc.b $E9, $0, $0, $10, $F8
DATAP0GAP5LACHB_5A: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $EC, $8, $0, $C, $F8
	dc.b $C, $8, $0, $F, $F8
DATAP0GAP5LACHB_5B: dc.b $2
	dc.b $EF, $F, $0, $0, $EE
	dc.b $F7, $0, $0, $10, $E
DATAP0GAP5LACHB_5C: dc.b $2
	dc.b $EF, $F, $0, $0, $ED
	dc.b $F7, $2, $0, $10, $D
DATAP0GAP5LACHB_5D: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
	even