; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 11 2021 12:47:15 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAM7KA4KFI8DM:
	dc.w $0, DATAM7KA4KFI8DM_1-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_2-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_3-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_4-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_5-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_6-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_7-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_8-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_9-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_A-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_D-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_E-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_F-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_10-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_11-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_12-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_13-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_14-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_15-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_16-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_17-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_18-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_19-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_1A-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_1B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_1C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_1D-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_1E-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_1F-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_20-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_21-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_22-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_23-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_24-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_25-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_26-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_27-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_28-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_29-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_2A-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_2B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_2C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_2D-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_2E-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_2F-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_30-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_31-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_32-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_33-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_34-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_35-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_36-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_37-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_38-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_39-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_3A-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_3B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_3C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_3D-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_3E-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_3F-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_40-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_41-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_42-DATAM7KA4KFI8DM, $0
	dc.w $0, DATAM7KA4KFI8DM_45-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_46-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_47-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_48-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_49-DATAM7KA4KFI8DM
	dc.w $0, DATAM7KA4KFI8DM_4B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_4C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_4D-DATAM7KA4KFI8DM
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAM7KA4KFI8DM_53-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_54-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_55-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_56-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_57-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_58-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_59-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_5A-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_5B-DATAM7KA4KFI8DM
	dc.w DATAM7KA4KFI8DM_5C-DATAM7KA4KFI8DM, DATAM7KA4KFI8DM_5D-DATAM7KA4KFI8DM
DATAM7KA4KFI8DM_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAM7KA4KFI8DM_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAM7KA4KFI8DM_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAM7KA4KFI8DM_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAM7KA4KFI8DM_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAM7KA4KFI8DM_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAM7KA4KFI8DM_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAM7KA4KFI8DM_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAM7KA4KFI8DM_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAM7KA4KFI8DM_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAM7KA4KFI8DM_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAM7KA4KFI8DM_C: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $6, $0, $9, $F3
	dc.b $FA, $8, $0, $F, $3
	dc.b $F2, $4, $0, $12, $B
DATAM7KA4KFI8DM_D: dc.b $5
	dc.b $EA, $A, $0, $0, $EE
	dc.b $F2, $0, $0, $9, $E6
	dc.b $FA, $5, $0, $A, $6
	dc.b $2, $5, $0, $E, $F6
	dc.b $12, $0, $0, $12, $FE
DATAM7KA4KFI8DM_E: dc.b $5
	dc.b $F8, $C, $0, $0, $E4
	dc.b $E8, $9, $0, $4, $EC
	dc.b $0, $8, $0, $A, $F4
	dc.b $8, $8, $0, $D, $FC
	dc.b $F8, $0, $0, $10, $4
DATAM7KA4KFI8DM_F: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $6, $0, $9, $F3
	dc.b $FA, $8, $0, $F, $3
	dc.b $F2, $4, $0, $12, $B
DATAM7KA4KFI8DM_10: dc.b $5
	dc.b $EA, $A, $0, $0, $EE
	dc.b $F2, $0, $0, $9, $E6
	dc.b $FA, $5, $0, $A, $6
	dc.b $2, $5, $0, $E, $F6
	dc.b $12, $0, $0, $12, $FE
DATAM7KA4KFI8DM_11: dc.b $4
	dc.b $E9, $A, $0, $0, $EC
	dc.b $1, $8, $0, $9, $F4
	dc.b $9, $8, $0, $C, $FC
	dc.b $F9, $0, $0, $F, $4
DATAM7KA4KFI8DM_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAM7KA4KFI8DM_13: dc.b $5
	dc.b $F2, $3, $0, $0, $F7
	dc.b $F2, $3, $0, $4, $F
	dc.b $FA, $5, $0, $8, $E7
	dc.b $FA, $6, $0, $C, $FF
	dc.b $A, $0, $0, $12, $EF
DATAM7KA4KFI8DM_14: dc.b $4
	dc.b $F9, $E, $0, $0, $ED
	dc.b $11, $0, $0, $C, $F5
	dc.b $F9, $2, $0, $D, $D
	dc.b $1, $1, $0, $10, $15
DATAM7KA4KFI8DM_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAM7KA4KFI8DM_16: dc.b $5
	dc.b $F2, $3, $0, $0, $F7
	dc.b $F2, $3, $0, $4, $F
	dc.b $FA, $5, $0, $8, $E7
	dc.b $FA, $6, $0, $C, $FF
	dc.b $A, $0, $0, $12, $EF
DATAM7KA4KFI8DM_17: dc.b $4
	dc.b $F9, $E, $0, $0, $ED
	dc.b $11, $0, $0, $C, $F5
	dc.b $F9, $2, $0, $D, $D
	dc.b $1, $1, $0, $10, $15
DATAM7KA4KFI8DM_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAM7KA4KFI8DM_19: dc.b $5
	dc.b $FD, $A, $0, $0, $EA
	dc.b $15, $0, $0, $9, $F2
	dc.b $ED, $5, $0, $A, $FA
	dc.b $FD, $5, $0, $E, $2
	dc.b $FD, $0, $0, $12, $12
DATAM7KA4KFI8DM_1A: dc.b $4
	dc.b $EF, $2, $0, $0, $8
	dc.b $F7, $6, $0, $3, $F8
	dc.b $FF, $6, $0, $9, $E8
	dc.b $F, $1, $0, $F, $F8
DATAM7KA4KFI8DM_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAM7KA4KFI8DM_1C: dc.b $5
	dc.b $FD, $A, $0, $0, $EA
	dc.b $15, $0, $0, $9, $F2
	dc.b $ED, $5, $0, $A, $FA
	dc.b $FD, $5, $0, $E, $2
	dc.b $FD, $0, $0, $12, $12
DATAM7KA4KFI8DM_1D: dc.b $4
	dc.b $F0, $2, $0, $0, $9
	dc.b $F8, $6, $0, $3, $F9
	dc.b $0, $6, $0, $9, $E9
	dc.b $10, $0, $0, $F, $F9
DATAM7KA4KFI8DM_1E: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAM7KA4KFI8DM_1F: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAM7KA4KFI8DM_20: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAM7KA4KFI8DM_21: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAM7KA4KFI8DM_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAM7KA4KFI8DM_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAM7KA4KFI8DM_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAM7KA4KFI8DM_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAM7KA4KFI8DM_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAM7KA4KFI8DM_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAM7KA4KFI8DM_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAM7KA4KFI8DM_29: dc.b $4
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $0, $0, $C, $F4
	dc.b $EE, $4, $0, $D, $4
	dc.b $F6, $1, $0, $F, $C
DATAM7KA4KFI8DM_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAM7KA4KFI8DM_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAM7KA4KFI8DM_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAM7KA4KFI8DM_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAM7KA4KFI8DM_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM7KA4KFI8DM_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAM7KA4KFI8DM_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM7KA4KFI8DM_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAM7KA4KFI8DM_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM7KA4KFI8DM_33: dc.b $3
	dc.b $F0, $7, $0, $0, $E8
	dc.b $F0, $7, $0, $8, $8
	dc.b $F0, $7, $0, $4, $F8
DATAM7KA4KFI8DM_34: dc.b $3
	dc.b $F0, $7, $0, $0, $EC
	dc.b $F0, $7, $0, $8, $4
	dc.b $F0, $7, $0, $4, $F8
DATAM7KA4KFI8DM_35: dc.b $2
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $0, $8, $0
DATAM7KA4KFI8DM_36: dc.b $3
	dc.b $F0, $7, $0, $0, $EB
	dc.b $F0, $7, $0, $8, $4
	dc.b $F0, $7, $0, $4, $F8
DATAM7KA4KFI8DM_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAM7KA4KFI8DM_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAM7KA4KFI8DM_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATAM7KA4KFI8DM_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAM7KA4KFI8DM_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAM7KA4KFI8DM_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAM7KA4KFI8DM_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAM7KA4KFI8DM_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAM7KA4KFI8DM_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAM7KA4KFI8DM_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAM7KA4KFI8DM_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAM7KA4KFI8DM_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAM7KA4KFI8DM_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATAM7KA4KFI8DM_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAM7KA4KFI8DM_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATAM7KA4KFI8DM_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAM7KA4KFI8DM_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAM7KA4KFI8DM_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM7KA4KFI8DM_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM7KA4KFI8DM_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM7KA4KFI8DM_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAM7KA4KFI8DM_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAM7KA4KFI8DM_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAM7KA4KFI8DM_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAM7KA4KFI8DM_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAM7KA4KFI8DM_58: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $8, $0, $C, $F6
	dc.b $F9, $1, $0, $F, $E
DATAM7KA4KFI8DM_59: dc.b $2
	dc.b $F0, $F, $0, $0, $F1
	dc.b $E8, $4, $0, $10, $F9
DATAM7KA4KFI8DM_5A: dc.b $3
	dc.b $F6, $E, $0, $0, $ED
	dc.b $EE, $8, $0, $C, $F5
	dc.b $F6, $1, $0, $F, $D
DATAM7KA4KFI8DM_5B: dc.b $2
	dc.b $F1, $F, $0, $0, $EC
	dc.b $F9, $2, $0, $10, $C
DATAM7KA4KFI8DM_5C: dc.b $3
	dc.b $EE, $B, $0, $0, $EF
	dc.b $E, $8, $0, $C, $F7
	dc.b $F6, $2, $0, $F, $7
DATAM7KA4KFI8DM_5D: dc.b $3
	dc.b $F0, $E, $0, $0, $F0
	dc.b $F8, $1, $0, $C, $E8
	dc.b $8, $8, $0, $E, $F0
	even