; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Oct 22 2020 10:49:42 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA7PQ40KBLQUL:
	dc.w $0, DATA7PQ40KBLQUL_1-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_2-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_3-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_4-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_5-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_6-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_7-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_8-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_9-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_A-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_D-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_E-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_F-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_10-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_11-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_12-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_13-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_14-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_15-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_16-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_17-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_18-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_19-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_1A-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_1B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_1C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_1D-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_1E-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_1F-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_20-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_21-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_22-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_23-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_24-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_25-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_26-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_27-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_28-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_29-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_2A-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_2B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_2C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_2D-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_2E-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_2F-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_30-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_31-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_32-DATA7PQ40KBLQUL, $0
	dc.w $0, $0
	dc.w $0, DATA7PQ40KBLQUL_37-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_38-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_39-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_3A-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_3B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_3C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_3D-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_3E-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_3F-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_40-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_41-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_42-DATA7PQ40KBLQUL, $0
	dc.w $0, DATA7PQ40KBLQUL_45-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_46-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_47-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_48-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_49-DATA7PQ40KBLQUL
	dc.w $0, DATA7PQ40KBLQUL_4B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_4C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_4D-DATA7PQ40KBLQUL
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATA7PQ40KBLQUL_53-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_54-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_55-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_56-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_57-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_58-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_59-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_5A-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_5B-DATA7PQ40KBLQUL
	dc.w DATA7PQ40KBLQUL_5C-DATA7PQ40KBLQUL, DATA7PQ40KBLQUL_5D-DATA7PQ40KBLQUL
DATA7PQ40KBLQUL_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATA7PQ40KBLQUL_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATA7PQ40KBLQUL_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATA7PQ40KBLQUL_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATA7PQ40KBLQUL_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATA7PQ40KBLQUL_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATA7PQ40KBLQUL_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATA7PQ40KBLQUL_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATA7PQ40KBLQUL_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATA7PQ40KBLQUL_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATA7PQ40KBLQUL_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATA7PQ40KBLQUL_C: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATA7PQ40KBLQUL_D: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATA7PQ40KBLQUL_E: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $EC, $9, $0, $4, $F0
	dc.b $4, $8, $0, $A, $F8
	dc.b $C, $8, $0, $D, $0
	dc.b $FC, $0, $0, $10, $8
DATA7PQ40KBLQUL_F: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATA7PQ40KBLQUL_10: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATA7PQ40KBLQUL_11: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $8, $0, $9, $F4
	dc.b $C, $8, $0, $C, $FC
	dc.b $FC, $0, $0, $F, $4
DATA7PQ40KBLQUL_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATA7PQ40KBLQUL_13: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATA7PQ40KBLQUL_14: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATA7PQ40KBLQUL_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATA7PQ40KBLQUL_16: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATA7PQ40KBLQUL_17: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATA7PQ40KBLQUL_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATA7PQ40KBLQUL_19: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATA7PQ40KBLQUL_1A: dc.b $4
	dc.b $E8, $2, $0, $0, $C
	dc.b $F0, $6, $0, $3, $FC
	dc.b $F8, $6, $0, $9, $EC
	dc.b $8, $1, $0, $F, $FC
DATA7PQ40KBLQUL_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATA7PQ40KBLQUL_1C: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATA7PQ40KBLQUL_1D: dc.b $4
	dc.b $EC, $2, $0, $0, $C
	dc.b $F4, $6, $0, $3, $FC
	dc.b $FC, $6, $0, $9, $EC
	dc.b $C, $0, $0, $F, $FC
DATA7PQ40KBLQUL_1E: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATA7PQ40KBLQUL_1F: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATA7PQ40KBLQUL_20: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATA7PQ40KBLQUL_21: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATA7PQ40KBLQUL_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATA7PQ40KBLQUL_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATA7PQ40KBLQUL_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATA7PQ40KBLQUL_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATA7PQ40KBLQUL_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATA7PQ40KBLQUL_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATA7PQ40KBLQUL_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATA7PQ40KBLQUL_29: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $C, $0, $0, $C, $F4
	dc.b $EC, $4, $0, $D, $4
	dc.b $F4, $1, $0, $F, $C
DATA7PQ40KBLQUL_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATA7PQ40KBLQUL_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATA7PQ40KBLQUL_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATA7PQ40KBLQUL_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATA7PQ40KBLQUL_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA7PQ40KBLQUL_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATA7PQ40KBLQUL_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA7PQ40KBLQUL_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATA7PQ40KBLQUL_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA7PQ40KBLQUL_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATA7PQ40KBLQUL_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATA7PQ40KBLQUL_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATA7PQ40KBLQUL_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATA7PQ40KBLQUL_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATA7PQ40KBLQUL_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATA7PQ40KBLQUL_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATA7PQ40KBLQUL_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATA7PQ40KBLQUL_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATA7PQ40KBLQUL_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATA7PQ40KBLQUL_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATA7PQ40KBLQUL_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATA7PQ40KBLQUL_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATA7PQ40KBLQUL_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATA7PQ40KBLQUL_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATA7PQ40KBLQUL_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATA7PQ40KBLQUL_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATA7PQ40KBLQUL_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATA7PQ40KBLQUL_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATA7PQ40KBLQUL_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATA7PQ40KBLQUL_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATA7PQ40KBLQUL_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATA7PQ40KBLQUL_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATA7PQ40KBLQUL_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATA7PQ40KBLQUL_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATA7PQ40KBLQUL_58: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATA7PQ40KBLQUL_59: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATA7PQ40KBLQUL_5A: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATA7PQ40KBLQUL_5B: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATA7PQ40KBLQUL_5C: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATA7PQ40KBLQUL_5D: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
	even