; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 12 2021 23:01:50 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAK5SJ6QUTA3:
	dc.w $0, DATAK5SJ6QUTA3_1-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_2-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_3-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_4-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_5-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_6-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_7-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_8-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_9-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_D-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_E-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_F-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_10-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_11-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_12-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_13-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_14-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_15-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_16-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_17-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_18-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_19-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_1A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_1B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_1C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_1D-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_1E-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_1F-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_20-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_21-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_22-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_23-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_24-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_25-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_26-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_27-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_28-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_29-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_2A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_2B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_2C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_2D-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_2E-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_2F-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_30-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_31-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_32-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_33-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_34-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_35-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_36-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_37-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_38-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_39-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_3A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_3B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_3C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_3D-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_3E-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_3F-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_40-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_41-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_42-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_43-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_44-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_45-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_46-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_47-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_48-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_49-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_4A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_4B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_4C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_4D-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_4E-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_4F-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_50-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_51-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_52-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_53-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_54-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_55-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_56-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_57-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_58-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_59-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_5A-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_5B-DATAK5SJ6QUTA3
	dc.w DATAK5SJ6QUTA3_5C-DATAK5SJ6QUTA3, DATAK5SJ6QUTA3_5D-DATAK5SJ6QUTA3
DATAK5SJ6QUTA3_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAK5SJ6QUTA3_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAK5SJ6QUTA3_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAK5SJ6QUTA3_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAK5SJ6QUTA3_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATAK5SJ6QUTA3_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAK5SJ6QUTA3_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATAK5SJ6QUTA3_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATAK5SJ6QUTA3_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATAK5SJ6QUTA3_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATAK5SJ6QUTA3_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAK5SJ6QUTA3_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAK5SJ6QUTA3_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAK5SJ6QUTA3_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAK5SJ6QUTA3_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAK5SJ6QUTA3_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAK5SJ6QUTA3_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAK5SJ6QUTA3_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAK5SJ6QUTA3_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAK5SJ6QUTA3_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAK5SJ6QUTA3_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAK5SJ6QUTA3_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAK5SJ6QUTA3_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAK5SJ6QUTA3_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAK5SJ6QUTA3_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAK5SJ6QUTA3_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAK5SJ6QUTA3_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAK5SJ6QUTA3_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAK5SJ6QUTA3_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAK5SJ6QUTA3_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAK5SJ6QUTA3_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAK5SJ6QUTA3_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAK5SJ6QUTA3_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAK5SJ6QUTA3_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAK5SJ6QUTA3_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAK5SJ6QUTA3_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAK5SJ6QUTA3_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAK5SJ6QUTA3_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAK5SJ6QUTA3_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAK5SJ6QUTA3_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAK5SJ6QUTA3_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAK5SJ6QUTA3_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAK5SJ6QUTA3_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAK5SJ6QUTA3_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAK5SJ6QUTA3_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAK5SJ6QUTA3_2E: dc.b $3
	dc.b $F1, $F, $0, $0, $F0
	dc.b $F5, $8, $0, $10, $EA
	dc.b $FD, $9, $0, $13, $EC
DATAK5SJ6QUTA3_2F: dc.b $3
	dc.b $F1, $F, $0, $0, $F0
	dc.b $F5, $8, $0, $10, $EA
	dc.b $FD, $9, $0, $13, $EC
DATAK5SJ6QUTA3_30: dc.b $3
	dc.b $F1, $F, $0, $0, $F0
	dc.b $F5, $8, $0, $10, $EA
	dc.b $FD, $9, $0, $13, $EC
DATAK5SJ6QUTA3_31: dc.b $3
	dc.b $F1, $F, $0, $0, $F0
	dc.b $F5, $8, $0, $10, $EA
	dc.b $FD, $9, $0, $13, $EC
DATAK5SJ6QUTA3_32: dc.b $3
	dc.b $F1, $F, $0, $0, $F0
	dc.b $F5, $8, $0, $10, $EA
	dc.b $FD, $9, $0, $13, $EC
DATAK5SJ6QUTA3_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAK5SJ6QUTA3_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAK5SJ6QUTA3_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAK5SJ6QUTA3_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAK5SJ6QUTA3_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAK5SJ6QUTA3_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAK5SJ6QUTA3_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATAK5SJ6QUTA3_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAK5SJ6QUTA3_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAK5SJ6QUTA3_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAK5SJ6QUTA3_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAK5SJ6QUTA3_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAK5SJ6QUTA3_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAK5SJ6QUTA3_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATAK5SJ6QUTA3_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAK5SJ6QUTA3_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAK5SJ6QUTA3_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAK5SJ6QUTA3_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAK5SJ6QUTA3_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAK5SJ6QUTA3_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAK5SJ6QUTA3_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAK5SJ6QUTA3_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAK5SJ6QUTA3_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAK5SJ6QUTA3_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAK5SJ6QUTA3_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAK5SJ6QUTA3_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAK5SJ6QUTA3_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAK5SJ6QUTA3_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAK5SJ6QUTA3_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAK5SJ6QUTA3_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAK5SJ6QUTA3_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAK5SJ6QUTA3_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAK5SJ6QUTA3_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAK5SJ6QUTA3_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAK5SJ6QUTA3_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAK5SJ6QUTA3_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAK5SJ6QUTA3_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAK5SJ6QUTA3_58: dc.b $4
	dc.b $F8, $D, $0, $0, $E8
	dc.b $E8, $9, $0, $8, $F0
	dc.b $8, $1, $0, $E, $0
	dc.b $F8, $5, $0, $10, $8
DATAK5SJ6QUTA3_59: dc.b $4
	dc.b $EC, $3, $0, $0, $EC
	dc.b $C, $4, $0, $4, $EC
	dc.b $F4, $E, $0, $6, $F4
	dc.b $EC, $4, $0, $12, $4
DATAK5SJ6QUTA3_5A: dc.b $4
	dc.b $0, $D, $0, $0, $EC
	dc.b $10, $8, $0, $8, $F4
	dc.b $E8, $2, $0, $B, $FC
	dc.b $F0, $5, $0, $E, $4
DATAK5SJ6QUTA3_5B: dc.b $4
	dc.b $F8, $C, $0, $0, $E8
	dc.b $0, $A, $0, $4, $F0
	dc.b $E8, $1, $0, $D, $F8
	dc.b $0, $5, $0, $F, $8
DATAK5SJ6QUTA3_5C: dc.b $4
	dc.b $EC, $7, $0, $0, $4
	dc.b $F4, $A, $0, $8, $EC
	dc.b $C, $4, $0, $11, $EC
	dc.b $C, $4, $0, $13, $4
DATAK5SJ6QUTA3_5D: dc.b $3
	dc.b $C, $C, $0, $0, $EC
	dc.b $EC, $B, $0, $4, $F4
	dc.b $F4, $0, $0, $10, $C
	even