; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 11 2021 10:00:16 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAFOU14K0JLO7:
	dc.w $0, DATAFOU14K0JLO7_1-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_2-DATAFOU14K0JLO7, DATAFOU14K0JLO7_3-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_4-DATAFOU14K0JLO7, DATAFOU14K0JLO7_5-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_6-DATAFOU14K0JLO7, DATAFOU14K0JLO7_7-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_8-DATAFOU14K0JLO7, DATAFOU14K0JLO7_9-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_A-DATAFOU14K0JLO7, DATAFOU14K0JLO7_B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_D-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_E-DATAFOU14K0JLO7, DATAFOU14K0JLO7_F-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_10-DATAFOU14K0JLO7, DATAFOU14K0JLO7_11-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_12-DATAFOU14K0JLO7, DATAFOU14K0JLO7_13-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_14-DATAFOU14K0JLO7, DATAFOU14K0JLO7_15-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_16-DATAFOU14K0JLO7, DATAFOU14K0JLO7_17-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_18-DATAFOU14K0JLO7, DATAFOU14K0JLO7_19-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_1A-DATAFOU14K0JLO7, DATAFOU14K0JLO7_1B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_1C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_1D-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_1E-DATAFOU14K0JLO7, DATAFOU14K0JLO7_1F-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_20-DATAFOU14K0JLO7, DATAFOU14K0JLO7_21-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_22-DATAFOU14K0JLO7, DATAFOU14K0JLO7_23-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_24-DATAFOU14K0JLO7, DATAFOU14K0JLO7_25-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_26-DATAFOU14K0JLO7, DATAFOU14K0JLO7_27-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_28-DATAFOU14K0JLO7, DATAFOU14K0JLO7_29-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_2A-DATAFOU14K0JLO7, DATAFOU14K0JLO7_2B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_2C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_2D-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_2E-DATAFOU14K0JLO7, DATAFOU14K0JLO7_2F-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_30-DATAFOU14K0JLO7, DATAFOU14K0JLO7_31-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_32-DATAFOU14K0JLO7, $0
	dc.w $0, $0
	dc.w $0, DATAFOU14K0JLO7_37-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_38-DATAFOU14K0JLO7, DATAFOU14K0JLO7_39-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_3A-DATAFOU14K0JLO7, DATAFOU14K0JLO7_3B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_3C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_3D-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_3E-DATAFOU14K0JLO7, DATAFOU14K0JLO7_3F-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_40-DATAFOU14K0JLO7, DATAFOU14K0JLO7_41-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_42-DATAFOU14K0JLO7, $0
	dc.w $0, DATAFOU14K0JLO7_45-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_46-DATAFOU14K0JLO7, DATAFOU14K0JLO7_47-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_48-DATAFOU14K0JLO7, DATAFOU14K0JLO7_49-DATAFOU14K0JLO7
	dc.w $0, DATAFOU14K0JLO7_4B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_4C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_4D-DATAFOU14K0JLO7
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAFOU14K0JLO7_53-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_54-DATAFOU14K0JLO7, DATAFOU14K0JLO7_55-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_56-DATAFOU14K0JLO7, DATAFOU14K0JLO7_57-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_58-DATAFOU14K0JLO7, DATAFOU14K0JLO7_59-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_5A-DATAFOU14K0JLO7, DATAFOU14K0JLO7_5B-DATAFOU14K0JLO7
	dc.w DATAFOU14K0JLO7_5C-DATAFOU14K0JLO7, DATAFOU14K0JLO7_5D-DATAFOU14K0JLO7
DATAFOU14K0JLO7_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAFOU14K0JLO7_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAFOU14K0JLO7_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAFOU14K0JLO7_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAFOU14K0JLO7_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAFOU14K0JLO7_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAFOU14K0JLO7_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAFOU14K0JLO7_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAFOU14K0JLO7_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAFOU14K0JLO7_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAFOU14K0JLO7_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAFOU14K0JLO7_C: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAFOU14K0JLO7_D: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAFOU14K0JLO7_E: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $EC, $9, $0, $4, $F0
	dc.b $4, $8, $0, $A, $F8
	dc.b $C, $8, $0, $D, $0
	dc.b $FC, $0, $0, $10, $8
DATAFOU14K0JLO7_F: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAFOU14K0JLO7_10: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAFOU14K0JLO7_11: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $8, $0, $9, $F4
	dc.b $C, $8, $0, $C, $FC
	dc.b $FC, $0, $0, $F, $4
DATAFOU14K0JLO7_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAFOU14K0JLO7_13: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAFOU14K0JLO7_14: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAFOU14K0JLO7_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAFOU14K0JLO7_16: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAFOU14K0JLO7_17: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAFOU14K0JLO7_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAFOU14K0JLO7_19: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAFOU14K0JLO7_1A: dc.b $4
	dc.b $E8, $2, $0, $0, $C
	dc.b $F0, $6, $0, $3, $FC
	dc.b $F8, $6, $0, $9, $EC
	dc.b $8, $1, $0, $F, $FC
DATAFOU14K0JLO7_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAFOU14K0JLO7_1C: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAFOU14K0JLO7_1D: dc.b $4
	dc.b $EC, $2, $0, $0, $C
	dc.b $F4, $6, $0, $3, $FC
	dc.b $FC, $6, $0, $9, $EC
	dc.b $C, $0, $0, $F, $FC
DATAFOU14K0JLO7_1E: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAFOU14K0JLO7_1F: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAFOU14K0JLO7_20: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAFOU14K0JLO7_21: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAFOU14K0JLO7_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAFOU14K0JLO7_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAFOU14K0JLO7_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAFOU14K0JLO7_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAFOU14K0JLO7_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAFOU14K0JLO7_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAFOU14K0JLO7_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAFOU14K0JLO7_29: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $C, $0, $0, $C, $F4
	dc.b $EC, $4, $0, $D, $4
	dc.b $F4, $1, $0, $F, $C
DATAFOU14K0JLO7_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAFOU14K0JLO7_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAFOU14K0JLO7_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAFOU14K0JLO7_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAFOU14K0JLO7_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAFOU14K0JLO7_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAFOU14K0JLO7_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAFOU14K0JLO7_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAFOU14K0JLO7_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAFOU14K0JLO7_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAFOU14K0JLO7_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAFOU14K0JLO7_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATAFOU14K0JLO7_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAFOU14K0JLO7_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAFOU14K0JLO7_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAFOU14K0JLO7_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAFOU14K0JLO7_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAFOU14K0JLO7_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAFOU14K0JLO7_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAFOU14K0JLO7_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAFOU14K0JLO7_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAFOU14K0JLO7_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATAFOU14K0JLO7_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAFOU14K0JLO7_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATAFOU14K0JLO7_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAFOU14K0JLO7_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAFOU14K0JLO7_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAFOU14K0JLO7_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAFOU14K0JLO7_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAFOU14K0JLO7_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAFOU14K0JLO7_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAFOU14K0JLO7_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAFOU14K0JLO7_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAFOU14K0JLO7_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAFOU14K0JLO7_58: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $8, $0, $C, $F6
	dc.b $F9, $1, $0, $F, $E
DATAFOU14K0JLO7_59: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $8, $0, $10, $F8
DATAFOU14K0JLO7_5A: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAFOU14K0JLO7_5B: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATAFOU14K0JLO7_5C: dc.b $3
	dc.b $F1, $E, $8, $0, $F6
	dc.b $9, $8, $8, $C, $F6
	dc.b $F9, $1, $8, $F, $EE
DATAFOU14K0JLO7_5D: dc.b $3
	dc.b $F9, $E, $18, $0, $F6
	dc.b $F1, $8, $18, $C, $F6
	dc.b $F9, $1, $18, $F, $EE
	even